const TH = {
  login_text_01: "สำหรับลูกบ้าน",
  login_text_02:
    "เข้าสู่ระบบด้วยเลขประจำตัวประชาชน หรือ\nหมายเลขหนังสือเดินทาง",
  login_text_03: "สำหรับสมาชิกทั่วไป",
  login_text_04: "เข้าใช้งานแบบสมาชิกทั่วไป",
  login_text_05: "ติดต่อเจ้าหน้าที่",
  login_text_06: "021 613 000",
  login_text_07: "เวอร์ชั่น",
  login_text_08: "เลือกภาษา",
  login_text_09: "ภาษาไทย",
  signin_text_01: "เข้าสู่ระบบ",
  signin_text_02: "เลขประจำตัวประชาชน / หมายเลขหนังสือเดินทาง",
  signin_text_03: "ถัดไป",
  otp_text_01: "เลือกวิธีรับ OTP",
  otp_text_02: "หมายเลขโทรศัพท์",
  otp_text_03: "อีเมล",
  otp_text_04: "หมายเลขโทรศัพท์ที่ต้องการรับ OTP",
  otp_text_05: "อีเมลที่ต้องการรับ OTP",
  otp_text_06: "ส่ง OTP",
  otp_text_07:
    "หากหมายเลขโทรศัพท์ หรืออีเมลของท่านไม่ถูกต้อง\nกรุณาติดต่อ Call Center โทร 021 613 000\nในวันเวลาทำการ 9:00-18:00 น.",
  inputotp_text_01: "OTP ได้ส่งไปยังเบอร์",
  inputotp_text_02: "OTP ได้ส่งไปยังอีเมล",
  inputotp_text_03: "รหัสอ้างอิง",
  inputotp_text_04: "รหัส OTP 6 หลัก",
  inputotp_text_05: "ยังไม่ได้รับรหัส OTP",
  inputotp_text_06: "ส่งอีกครั้ง",
  inputotp_text_07: "เข้าสู่ระบบ",
  inputotp_text_08: "ในอีก",
  inputotp_text_09: "วินาที",
  home_text_01: "ยินดีต้อนรับ คุณ",
  home_text_02: "ข่าวสาร & กิจกรรม",
  home_text_03: "หน้าหลัก",
  home_text_04: "ข้อมูลบ้าน",
  home_text_05: "บัญชี",
  notify_text_01: "แจ้งเตือน",
  notify_text_02: "ทั้งหมด",
  notify_text_03: "ข่าวสาร",
  notify_text_04: "แจ้งซ่อม",
  notify_text_05: "อ่านทั้งหมด",
  notify_text_06: "ไม่พบการแจ้งเตือน",
  account_text_01: "บัญชี",
  account_text_02: "ข้อมูลส่วนตัว",
  account_text_03: "จัดการข้อมูลผู้อาศัย / ผู้เช่า",
  account_text_04: "ตั้งค่าภาษา",
  account_text_05: "นโยบายความเป็นส่วนตัว",
  account_text_06: "คอลเซ็นเตอร์",
  account_text_07: "ออกจากระบบ",
  account_text_08: "เวอร์ชั่น",
  account_text_09: "ยืนยัน",
  account_text_10: "ยกเลิก",
  account_text_11: "ยืนยันการออกจากระบบ",
  profile_text_01: "ข้อมูลส่วนตัว",
  profile_text_02: "ชื่อ-นามสกุล",
  profile_text_03: "เบอร์โทรศัพท์",
  profile_text_04: "บันทึก",
  profile_text_05: "ยกเลิก",
  myhome_text_01: "ที่ดินขนาด",
  myhome_text_02: "ตารางวา",
  myhome_text_03: "พื้นที่ใช้สอย",
  myhome_text_04: "ตารางเมตร",
  myhome_text_05: "แจ้งซ่อม",
  myhome_text_06: "ไม่พบยูนิตที่ท่านครอบครองอยู่",
  myhome_text_07: "ขออภัยค่ะ\nจากการตรวจสอบ การรับประกันบ้านของท่านได้สิ้นสุดลงแล้ว",
  myhome_text_08: "สอบถามข้อมูลเพิ่มเติมกรุณาติดต่อ\nCall center 02-161-3000\nบริทาเนีย คำตอบของทุกครอบครัว",
  myhome_text_09: "ปิด",
  homecare_text_01: "แจ้งซ่อม",
  homecare_text_02: "บ้านเลขที่",
  homecare_text_03: "รายการแจ้งซ่อม",
  homecare_text_04: "ประวัติแจ้งซ่อม",
  homecare_text_05: "ไม่มีข้อมูลแจ้งซ่อม",
  homecare_text_06: "เพิ่มรายการแจ้งซ่อม",
  homecare_text_07: "เลขแจ้งซ่อม",
  homecare_text_08: "จำนวนรายการ",
  homecare_text_09: "วันที่และเวลาแจ้งซ่อม",
  homecare_text_10: "วันที่และเวลาที่เข้ารับบริการ",
  homecare_text_11: "รายการ",
  homecare_text_12: "ประเภท",
  homecare_text_13: "การประเมินความพึงพอใจ",
  homecare_text_14: "รอประเมิน",
  homecare_text_15: "รายละเอียด",
  homecare_text_16: "รูปภาพ",
  homecare_text_17: "เจ้าหน้าที่ โฮมแคร์ที่เข้าตรวจสอบ",
  homecare_text_18: "ตรวจสอบหน้างาน",
  homecare_text_19: "เข้าซ่อม",
  homecare_text_20: "ประเมินแล้ว",
  homecare_text_21: "การประเมินความพึงพอใจ",
  homecare_text_22: "เจ้าหน้าที่ โฮมแคร์ที่เข้าตรวจสอบ",
  homecare_text_23: "เบอร์โทรศัพท์",
  homecare_text_24: "Line ID",
  homecare_text_25: "ไม่พบ เจ้าหน้าที่โฮมแคร์ที่เข้าตรวจสอบ",
  homecare_text_26: "ชื่อ-นามสกุล",
  homecare_text_27: "เจ้าหน้าที่ โฮมแคร์ที่เข้าตรวจสอบหน้างาน",
  homecare_text_27_1: "วันที่และเวลาตรวจสอบหน้างาน",
  homecare_text_28: "ตรวจหน้างานเรียบร้อย",
  homecare_text_29: "รายการตรวจสอบ",
  homecare_text_30: "หมายเหตุ",
  homecare_text_31: "ไม่พบรายการตรวจสอบหน้างาน",
  homecare_text_32: "เจ้าหน้าที่ โฮมแคร์ที่เข้าซ่อม",
  homecare_text_33: "อยู่ระหว่างดำเนินการ",
  homecare_text_34: "ขั้นตอนการทำงาน",
  homecare_text_35: "1.ก่อนปฏิบัติงาน",
  homecare_text_36: "2.อุปกรณ์ป้องกันวัสดุ",
  homecare_text_37: "3.เวลาขณะปฏิบัติงาน",
  homecare_text_38: "วันที่และเวลาเข้าซ่อม",
  homecare_text_39: "ไม่พบรายการแก้ไข",
  homecare_text_40: "ไม่พบรายการแก้ไข",
  homecare_text_41: "โครงการของฉัน",
  membermanage_text_01: "จัดการข้อมูลผู้อาศัย / ผู้เช่า",
  membermanage_text_02: "เบลกราเวีย เอ็กซ์คลูซีฟ พูลวิลล่า บางนา พระราม 9",
  membermanage_text_03: "บริทาเนีย บางนา กม.12",
  membermanage_text_04: "บ้านเลขที่",
  membermanageindivi_text_01: "ผู้อาศัยร่วม",
  membermanageindivi_text_02: "ผู้เช่า",
  membermanageindivi_text_03: "เพิ่มผู้อาศัยร่วม",
  membermanageindivi_text_04: "ไม่มีผู้อาศัยร่วม",
  membermanageindivi_text_05: "ยังไม่เปิดใช้งาน",
  membermanageindivi_text_06: "ชื่อ-นามสกุล",
  membermanageindivi_text_07: "เบอร์โทรศัพท์",
  membermanageindivi_text_08: "อีเมล",
  membermanageindivi_text_09: "กรอก OTP เพื่อเปิดใช้งาน",
  membermanageindivi_text_10: "สิทธิ์หมดอายุ",
  membermanageindivi_text_11: "เปิดการใช้งานแล้ว",
  membermanageindivi_text_12: "เพิ่มผู้เช่า",
  residentadd_text_01: "เพิ่มผู้อาศัยร่วม",
  residentadd_text_02: "ผู้อาศัยร่วม",
  residentadd_text_03: "บุคคลสัญชาติไทย",
  residentadd_text_04: "บุคคลต่างชาติ",
  residentadd_text_05: "ชื่อ-นามสกุล",
  residentadd_text_06: "เลขประจำตัวบัตรประชาชน",
  residentadd_text_07: "เบอร์โทรศัพท์",
  residentadd_text_08: "อีเมล",
  residentadd_text_09: "ยืนยัน",
  residentadd_text_10: "ยกเลิก",
  residentadd_text_11: "หมายเลขหนังสือเดินทาง",
  residentaddotp_text_01: "เพิ่มผู้อาศัยร่วม",
  residentaddotp_text_02: "กรุณากรอกรหัส OTP ที่ส่งไปยังคุณ",
  residentaddotp_text_031: "หมายเลข ",
  residentaddotp_text_032: " เพื่อเปิดสิทธิ์การใช้งาน",
  residentaddotp_text_04: "รหัส OTP 6 หลัก",
  residentaddotp_text_05: "ยังไม่ได้รับรหัส OTP",
  residentaddotp_text_06: "ส่งอีกครั้ง",
  residentaddotp_text_07: "ยืนยัน",
  residentaddotp_text_08: "ข้าม",
  residentdetail_text_01: "ผู้อาศัยร่วม",
  residentdetail_text_02: "เปิดการใช้งานแล้ว",
  residentdetail_text_03: "ชื่อ-นามสกุล",
  residentdetail_text_04: "เบอร์โทรศัพท์",
  residentdetail_text_05: "อีเมล",
  residentdetail_text_06: "ลบ",
  residentdetail_text_07: "แก้ไข",
  residentdetail_text_08: "ยังไม่เปิดใช้งาน",
  residentdetail_text_09: "ยืนยันการลบผู้อาศัยร่วม",
  residentedit_text_01: "แก้ไขผู้อาศัยร่วม",
  residentedit_text_02: "เพิ่มผู้อาศัยร่วม",
  residentedit_text_03: "ผู้อาศัยร่วม",
  residentedit_text_04: "บุคคลสัญชาติไทย",
  residentedit_text_05: "บุคคลต่างชาติ",
  residentedit_text_06: "ชื่อ-นามสกุล",
  residentedit_text_07: "เลขประจำตัวบัตรประชาชน",
  residentedit_text_08: "เบอร์โทรศัพท์",
  residentedit_text_09: "อีเมล",
  residentedit_text_10: "ยืนยัน",
  residentedit_text_11: "ยกเลิก",
  residentedit_text_12: "หมายเลขหนังสือเดินทาง",
  residentedit_text_13: "บันทึก",
  occupantadd_text_01: "เพิ่มผู้เช่า",
  occupantadd_text_02: "ผู้เช่า",
  occupantadd_text_03: "บุคคลสัญชาติไทย",
  occupantadd_text_04: "บุคคลต่างชาติ",
  occupantadd_text_05: "ชื่อ-นามสกุล",
  occupantadd_text_06: "เลขประจำตัวบัตรประชาชน",
  occupantadd_text_07: "เบอร์โทรศัพท์",
  occupantadd_text_08: "อีเมล",
  occupantadd_text_09: "บันทึก",
  occupantadd_text_10: "ยกเลิก",
  occupantadd_text_11: "หมายเลขหนังสือเดินทาง",
  occupantadd_text_12: "วันที่สิทธิ์หมดอายุ",
  occupantaddotp_text_01: "เพิ่มผู้เช่า",
  occupantaddotp_text_02: "กรุณากรอกรหัส OTP ที่ส่งไปยังคุณ",
  occupantaddotp_text_03: "หมายเลข",
  occupantaddotp_text_03_1: "เพื่อเปิดสิทธิ์การใช้งาน",
  occupantaddotp_text_04: "รหัส OTP 6 หลัก",
  occupantaddotp_text_05: "ยังไม่ได้รับรหัส OTP",
  occupantaddotp_text_06: "ส่งอีกครั้ง",
  occupantaddotp_text_07: "ยืนยัน",
  occupantaddotp_text_08: "ข้าม",
  occupantdetail_text_01: "ผู้เช่า",
  occupantdetail_text_02: "เปิดการใช้งานแล้ว",
  occupantdetail_text_03: "ชื่อ-นามสกุล",
  occupantdetail_text_04: "เบอร์โทรศัพท์",
  occupantdetail_text_05: "อีเมล",
  occupantdetail_text_06: "ลบ",
  occupantdetail_text_07: "แก้ไข",
  occupantdetail_text_08: "จัดการเมนู",
  occupantdetail_text_09: "เลือกเมนูที่ต้องการให้ผู้เช่าสามารถมองเห็นได้",
  occupantdetail_text_10: "แจ้งซ่อม",
  occupantdetail_text_11: "สิทธิ์หมดอายุ",
  occupantdetail_text_12: "ยังไม่เปิดใช้งาน",
  occupantedit_text_01: "แก้ไขผู้เช่า",
  occupantedit_text_02: "เพิ่มผู้เช่า",
  occupantedit_text_03: "ผู้เช่า",
  occupantedit_text_04: "บุคคลสัญชาติไทย",
  occupantedit_text_05: "บุคคลต่างชาติ",
  occupantedit_text_06: "ชื่อ-นามสกุล",
  occupantedit_text_07: "เลขประจำตัวบัตรประชาชน",
  occupantedit_text_08: "เบอร์โทรศัพท์",
  occupantedit_text_09: "อีเมล",
  occupantedit_text_10: "บันทึก",
  occupantedit_text_11: "ยกเลิก",
  occupantedit_text_12: "หมายเลขหนังสือเดินทาง",
  occupantedit_text_13: "วันสิทธิ์หมดอายุ",
  satisfaction_text_01: "ประเมินความพึงพอใจ",
  satisfaction_text_02: "เจ้าหน้าที่โฮมแคร์ที่เข้าซ่อม",
  satisfaction_text_03: "1 = พึงพอใจน้อยที่สุด",
  satisfaction_text_04: "5 = พึงพอใจมากที่สุด",
  satisfaction_text_05: "ชมเชย / ข้อเสนอแนะ",
  satisfaction_text_06: "กรุณาให้คะแนนอย่างน้อย 1 ดาว",
  satisfaction_text_07: "ประเมินแล้ว",
  alert_text_01: "กรุณาระบุข้อมูลให้ครบถ้วน",
  type_text_01: "แจ้งซ่อม",
  type_text_02: "เลือกประเภท",
  informadd_text_01: "แจ้งซ่อม",
  informadd_text_02: "ข้อมูลเพิ่มเติม",
  informadd_text_03: "รูปภาพ",
  informadd_text_04: "เพิ่มรูป",
  informadd_text_05: "รายละเอียด",
  informadd_text_06: "ยืนยัน",
  informadd_text_07: 'กรุณาระบุ "รายละเอียด"',
  informcontact_text_01: "แจ้งซ่อม",
  informcontact_text_02: "ห้องที่ต้องการแจ้งซ่อม",
  informcontact_text_03: "ชื่อ-นามสกุล",
  informcontact_text_04: "เบอร์โทรศัพท์",
  informcontact_text_05: "รายการแจ้งซ่อม",
  informcontact_text_06: "ประเภท",
  informcontact_text_07: "รายละเอียด",
  informcontact_text_08: "รูปภาพ",
  informcontact_text_09: "หมายเหตุ",
  informcontact_text_10: "เพิ่มรายการ",
  informcontact_text_11: "ถัดไป",
  informcalendar_text_01: "เลือกวันที่และเวลา",
  informcalendar_text_02: "เลือกวันที่รับบริการ",
  informcalendar_text_03: "เลือกเวลา",
  informcalendar_text_04: "ยืนยัน",
  informcalendar_text_05: "เจ้าหน้าที่ โฮมแคร์จะติดต่อกลับเพื่อยืนยันนัดหมาย ภายในวันทำการถัดไป",
  informcalendar_text_06: "ตกลง",
  informcalendar_text_07: "งดให้บริการเนื่องจาก",
};

const EN = {
  login_text_01: "For user",
  login_text_02: "Log in with your id card and\n passport number",
  login_text_03: "For guest user",
  login_text_04: "Log in as guest user",
  login_text_05: "CALL CENTER",
  login_text_06: "021 613 000",
  login_text_07: "VERSION",
  login_text_08: "Choose your language",
  login_text_09: "THAI",
  signin_text_01: "Login",
  signin_text_02: "ID NUMBER / Passport Number",
  signin_text_03: "Next",
  otp_text_01: "Choose options to receive OTP",
  otp_text_02: "Phone ",
  otp_text_03: "E-mail",
  otp_text_04: "Your phone number to receive OTP",
  otp_text_05: "Your E-mail Address to receive OTP",
  otp_text_06: "SEND OTP",
  otp_text_07:
    "REMARK: If your phone number or E-MAIL are invalid\nPlease contact call center : 021 613 000\nAT 9:00 – 18:00",
  inputotp_text_01: "OTP is sent to",
  inputotp_text_02: "OTP is sent to",
  inputotp_text_03: "Reference code",
  inputotp_text_04: "OTP password",
  inputotp_text_05: "Did not receive OTP",
  inputotp_text_06: "Send again",
  inputotp_text_07: "Login",
  inputotp_text_08: " will send in",
  inputotp_text_09: "sec.",
  home_text_01: "Welcome",
  home_text_02: "News & Events",
  home_text_03: "HOME",
  home_text_04: "HOME DATA",
  home_text_05: "ACCOUNT",
  notify_text_01: "Notification",
  notify_text_02: "All",
  notify_text_03: "News",
  notify_text_04: "Request Maintenance Service",
  notify_text_05: "Read all",
  notify_text_06: "Notification not found",
  account_text_01: "Account",
  account_text_02: "Personal Information",
  account_text_03: "Manage Resident / Tenants Information",
  account_text_04: "Language",
  account_text_05: "Privacy Policy ",
  account_text_06: "Call Center",
  account_text_07: "Sign Out",
  account_text_08: "Version",
  account_text_09: "Confirm",
  account_text_10: "Cancel",
  account_text_11: "Confirm Sign Out .",
  profile_text_01: "Personal Information",
  profile_text_02: "Name - Surname",
  profile_text_03: "Telephone",
  profile_text_04: "Save",
  profile_text_05: "Cancel",
  myhome_text_01: "Land size",
  myhome_text_02: "sq.Wa",
  myhome_text_03: "Usable area",
  myhome_text_04: "sq.m",
  myhome_text_05: "Request Maintenance Service",
  myhome_text_06: "Unit Owner not found",
  myhome_text_07: "Sorry\nYour home warranty has expired.",
  myhome_text_08: "For more information, please contact\nCall center 02-161-3000\nBritannia. Answers for every family.",
  myhome_text_09: "Close",
  homecare_text_01: "Request Maintenance Service",
  homecare_text_02: "Home Address",
  homecare_text_03: "List of maintenance",
  homecare_text_04: "History",
  homecare_text_05: "No maintenance notice",
  homecare_text_06: "Add item",
  homecare_text_07: "Case number",
  homecare_text_08: "Amount",
  homecare_text_09: "Date and time for maintenance",
  homecare_text_10: "Date and time to service appointment",
  homecare_text_11: "Item",
  homecare_text_12: "Category",
  homecare_text_13: "Customer Satisfaction Survey",
  homecare_text_14: "Processing",
  homecare_text_15: "Details",
  homecare_text_16: "Photo",
  homecare_text_17: "Home care officer who check",
  homecare_text_18: "Check on site",
  homecare_text_19: "Edit list",
  homecare_text_20: "Success",
  homecare_text_21: "Evaluation",
  homecare_text_22: "Home care officer who check",
  homecare_text_23: "Phone Number",
  homecare_text_24: "Line ID",
  homecare_text_25: "Home care officer who check not found",
  homecare_text_26: "Name-Surnane",
  homecare_text_27: "Home care officer who check on site",
  homecare_text_27_1: "Date and time for maintenance",
  homecare_text_28: "Success",
  homecare_text_29: "Item list",
  homecare_text_30: "Note",
  homecare_text_31: "Check on site not found",
  homecare_text_32: "Home care officer",
  homecare_text_33: "In process",
  homecare_text_34: "Work Process",
  homecare_text_35: "1.Before",
  homecare_text_36: "2.Doing",
  homecare_text_37: "3.Protection",
  homecare_text_38: "Date and time for maintenance",
  homecare_text_39: "Edit list not found",
  homecare_text_41: "My Account",
  membermanage_text_01: "Mange your Home address / Tenant",
  membermanage_text_02: "BELGRAVIA Exclusive Pool Villa Bangna",
  membermanage_text_03: "Britania Bangna KM.12",
  membermanage_text_04: "Home Address",
  membermanageindivi_text_01: "Co-resident",
  membermanageindivi_text_02: "Tenant",
  membermanageindivi_text_03: "Add co-resident",
  membermanageindivi_text_04: "Data not found",
  membermanageindivi_text_05: "No activated",
  membermanageindivi_text_06: "Name - Surname",
  membermanageindivi_text_07: "Telephone",
  membermanageindivi_text_08: "E-Mail",
  membermanageindivi_text_09: "ENTER OTP TO ACTIVATE YOUR ACCOUNT ",
  membermanageindivi_text_10: "Expiried Date",
  membermanageindivi_text_11: "Activated",
  membermanageindivi_text_12: "Add Tenant",
  residentadd_text_01: "Add Co-resident",
  residentadd_text_02: "Co-resident",
  residentadd_text_03: "Thai",
  residentadd_text_04: "Foreigner",
  residentadd_text_05: "Name - Surname",
  residentadd_text_06: "ID number",
  residentadd_text_07: "Telephone",
  residentadd_text_08: "E-Mail",
  residentadd_text_09: "Confirm",
  residentadd_text_10: "Cancel",
  residentadd_text_11: "Passport Number",
  residentaddotp_text_01: "Add Co-resident",
  residentaddotp_text_02: "Please enter OTP number that we sent to",
  residentaddotp_text_031: "Number : ",
  residentaddotp_text_032: " for activate your account.",
  residentaddotp_text_04: "6 OTP DIGIT PASSWORD",
  residentaddotp_text_05: "Did not receive OTP?",
  residentaddotp_text_06: "Send again",
  residentaddotp_text_07: "Confirm",
  residentaddotp_text_08: "Skip",
  residentdetail_text_01: "Co-resident",
  residentdetail_text_02: "Activated",
  residentdetail_text_03: "Name - Surname",
  residentdetail_text_04: "Telephone",
  residentdetail_text_05: "E-Mail",
  residentdetail_text_06: "Delete",
  residentdetail_text_07: "Edit",
  residentdetail_text_08: "No activated",
  residentdetail_text_09: "Confirm delete",
  residentedit_text_01: "Edit your Co-resident",
  residentedit_text_02: "Add Co-resident",
  residentedit_text_03: "Co-resident",
  residentedit_text_04: "Thai",
  residentedit_text_05: "Foreigner",
  residentedit_text_06: "Name - Surname",
  residentedit_text_07: "ID number",
  residentedit_text_08: "Telephone",
  residentedit_text_09: "E-Mail",
  residentedit_text_10: "Confirm",
  residentedit_text_11: "Cancel",
  residentedit_text_12: "Passport Number",
  residentedit_text_13: "Save",
  occupantadd_text_01: "Add Tenant",
  occupantadd_text_02: "Tenant",
  occupantadd_text_03: "Thai",
  occupantadd_text_04: "Foreigner",
  occupantadd_text_05: "Name - Surname",
  occupantadd_text_06: "ID number",
  occupantadd_text_07: "Telephone",
  occupantadd_text_08: "E-Mail",
  occupantadd_text_09: "Save",
  occupantadd_text_10: "Cancel",
  occupantadd_text_11: "Passport Number",
  occupantadd_text_12: "Expiried Date",
  occupantaddotp_text_01: "Add Tenant",
  occupantaddotp_text_02:
    "Please enter OTP number that we sent to",
  occupantaddotp_text_03: "Number :",
  occupantaddotp_text_03_1: "activate your account.",
  occupantaddotp_text_04: "6 OTP DIGIT PASSWORD",
  occupantaddotp_text_05: "Did not receive OTP?",
  occupantaddotp_text_06: "Send again",
  occupantaddotp_text_07: "Confirm",
  occupantaddotp_text_08: "Skip",
  occupantdetail_text_01: "Tenant",
  occupantdetail_text_02: "Activated",
  occupantdetail_text_03: "Name - Surname",
  occupantdetail_text_04: "Telephone",
  occupantdetail_text_05: "E-Mail",
  occupantdetail_text_06: "Delete",
  occupantdetail_text_07: "Edit",
  occupantdetail_text_08: "Manage your menu",
  occupantdetail_text_09: "Select the menu that tenant can see it",
  occupantdetail_text_10: "Request Maintenance Service",
  occupantdetail_text_11: "Expiried Date",
  occupantdetail_text_12: "No activated",
  occupantedit_text_01: "Edit your Tenant",
  occupantedit_text_02: "Add Tenant",
  occupantedit_text_03: "Tenant",
  occupantedit_text_04: "Thai",
  occupantedit_text_05: "Foreigner",
  occupantedit_text_06: "Name - Surname",
  occupantedit_text_07: "ID number",
  occupantedit_text_08: "Telephone",
  occupantedit_text_09: "E-Mail",
  occupantedit_text_10: "Save",
  occupantedit_text_11: "Cancel",
  occupantedit_text_12: "Passport Number",
  occupantedit_text_13: "Expiried Date",
  satisfaction_text_01: "Customer Satisfaction Survey",
  satisfaction_text_02: "Home care officer",
  satisfaction_text_03: "1 = Least satisfied",
  satisfaction_text_04: "5 = Very satisfied",
  satisfaction_text_05: "Suggestion",
  satisfaction_text_06: "Please rate at least 1 star.",
  satisfaction_text_07: "Success",
  alert_text_01: "Please provide complete information.",
  type_text_01: "Request Maintenance Service",
  type_text_02: "Choose your categories",
  informadd_text_01: "Request Maintenance Service",
  informadd_text_02: "Additional Information",
  informadd_text_03: "Photo",
  informadd_text_04: "Add photo",
  informadd_text_05: "Detail",
  informadd_text_06: "Confirm",
  informadd_text_07: 'Please specify "details"',
  informcontact_text_01: "Request Maintenance Service",
  informcontact_text_02: "Address to maintenance",
  informcontact_text_03: "Name - Surname",
  informcontact_text_04: "Telephone",
  informcontact_text_05: "List of maintenance",
  informcontact_text_06: "Categories",
  informcontact_text_07: "Details",
  informcontact_text_08: "Photos",
  informcontact_text_09: "Note",
  informcontact_text_10: "Add item",
  informcontact_text_11: "Next",
  informcalendar_text_01: "Make an appointment",
  informcalendar_text_02: "Select date and time",
  informcalendar_text_03: "Select time",
  informcalendar_text_04: "Confirm",
  informcalendar_text_05: "We received your request. Homecare Officer will call back to confirm the appointment the next day.",
  informcalendar_text_06: "OK",
  informcalendar_text_07: "Service is not available due to holidays.",
  //type
  type_1: "Electricity",
  type_2: "water pipe system /atmosphere good / bad",
  type_3: "Door",
  type_4: "Floor",
  type_5: "Ceiling",
  type_6: "Plumbing / Devices",
  type_7: "Structure",
  type_8: "Wall",
  type_9: "Paint",
  type_10: "Furniture",
  type_11: "Roof",
  type_12: "Common Area",
  type_13: "Others"
};

const settingLanguage = (lang) => {
  var setting_LANG;
  if (lang === "TH") {
    setting_LANG = TH;
  } else if (lang === "EN") {
    setting_LANG = EN;
  } else {
    setting_LANG = TH;
  }
  return setting_LANG;
};

export default {
  settingLanguage,
};
