const TH = {
  login_text_01 : "สำหรับลูกบ้าน",
  login_text_02 : "เข้าสู่ระบบด้วยเลขประจำตัวประชาชน หรือ\nหมายเลขหนังสือเดินทาง",
  login_text_03 : "สำหรับสมาชิกทั่วไป",
  login_text_04 : "เข้าใช้งานแบบสมาชิกทั่วไป",
  login_text_05 : "ติดต่อเจ้าหน้าที่",
  login_text_06 : "021 613 000",
  login_text_07 : "เวอร์ชั่น",
  login_text_08 : "เลือกภาษา",
  login_text_09 : "ภาษาไทย",
  signin_text_01 : "เข้าสู่่ระบบ",
  signin_text_02 : "เลขประจำตัวประชาชน / หมายเลขหนังสือเดินทาง",
  signin_text_03 : "ถัดไป",
  otp_text_01: "เลือกวิธีรับ OTP",
  otp_text_02: "หมายเลขโทรศัพท์",
  otp_text_03: "อีเมล",
  otp_text_04: "หมายเลขโทรศัพท์ที่ต้องการรับ OTP",
  otp_text_05: "อีเมลที่ต้องการรับ OTP",
  otp_text_06: "ส่ง OTP",
  otp_text_07: "หากหมายเลขโทรศัพท์ หรืออีเมลของท่านไม่ถูกต้อง\nกรุณาติดต่อ Call Center โทร 021 613 000\nในวันเวลาทำการ 9:00-18:00 น.",
  inputotp_text_01: "OTP ได้ส่งไปยังเบอร์",
  inputotp_text_02: "OTP ได้ส่งไปยังอีเมล",
  inputotp_text_03: "รหัสอ้างอิง",
  inputotp_text_04: "รหัส OTP 6 หลัก",
  inputotp_text_05: "ยังไม่ได้รับรหัส OTP ส่งอีกครั้ง",
  inputotp_text_06: "ส่งอีกครั้ง",
  inputotp_text_07: "เข้าสู่ระบบ",
  home_text_01: "ยินดีต้อนรับ",
  home_text_02: "ข่าวสาร & กิจกรรม",
  home_text_03: "หน้าหลัก",
  home_text_04: "ข้อมูลบ้าน",
  home_text_05: "บัญชี",
  notify_text_01: "แจ้งเตือน",
  notify_text_02: "ทั้งหมด",
  notify_text_03: "ข่าวสาร",
  notify_text_04: "แจ้งซ่อม",
  notify_text_05: "อ่านทั้งหมด",
  account_text_01: "บัญชี",
  account_text_02: "ข้อมูลส่วนตัว",
  account_text_03: "จัดการข้อมูลผู้อาศัย / ผู้เช่า",
  account_text_04: "ตั้งค่าภาษา",
  account_text_05: "นโยบายความเป้นส่วนตัว",
  account_text_06: "คอลเซ็นเตอร์",
  account_text_07: "ออกจากระบบ",
  account_text_08: "เวอร์ชั่น",
  account_text_09: "ยืนยัน",
  account_text_10: "ยกเลิก",
  account_text_11: "ยืนยันการออกจากระบบ",
  profile_text_01: "ข้อมูลส่วนตัว",
  profile_text_02: "ชื่อ-นามสกุล",
  profile_text_03: "เบอร์โทรศัพท์",
  profile_text_04: "บันทึก",
  profile_text_05: "ยกเลิก",
  myhome_text_01: "ที่ดินขนาด",
  myhome_text_02: "ตารางวา",
  myhome_text_03: "พื้นที่ใช้สอย",
  myhome_text_04: "ตารางเมตร",
  myhome_text_05: "แจ้งซ่อม",
  homecare_text_01: "แจ้งซ่อม",
  homecare_text_02: "บ้านเลขที่",
  homecare_text_03: "รายการแจ้งซ่อม",
  homecare_text_04: "ประวัติแจ้งซ่อม",
  homecare_text_05: "ไม่มีข้อมูลแจ้งซ่อม",
  homecare_text_06: "เพิ่มรายการแจ้งซ่อม",
  homecare_text_07: "เลขแจ้งซ่อม",
  homecare_text_08: "จำนวนรายการ",
  homecare_text_09: "วันที่และเวลาแจ้งซ่อม",
  homecare_text_10: "วันที่และเวลาที่เข้ารับบริการ",
  homecare_text_11: "รายการ",
  homecare_text_12: "ประเภท",
  homecare_text_13: "การประเมินความพึงพอใจ",
  homecare_text_14: "รอประเมิน",
  homecare_text_15: "รายละเอียด",
  homecare_text_16: "รูปภาพ",
  homecate_text_17: "เจ้าหน้าที่ โฮมแคร์ที่เข้าตรวจสอบ",
  homecare_text_18: "ตรวจสอบหน้างาน",
  homecare_text_19: "รายการแก้ไข",
}

const EN = {
  login_text_01 : "For user",
  login_text_02 : "Log in with your id card and\n passport number",
  login_text_03 : "For guest user",
  login_text_04 : "Log in as guest user",
  login_text_05 : "CALL CENTER",
  login_text_06 : "021 613 000",
  login_text_07 : "VERSION",
  login_text_08 : "Choose your language",
  login_text_09 : "THAI",
  signin_text_01 : "Login",
  signin_text_02 : "ID NUMBER / Passport Number",
  signin_text_03 : "Next",
  otp_text_01: "Choose options to receive OTP",
  otp_text_02: "Phone ",
  otp_text_03: "E-mail",
  otp_text_04: "Your phone number to receive OTP",
  otp_text_05: "Your E-mail Address to receive OTP",
  otp_text_06: "SEND OTP",
  otp_text_07: "REMARK: If your phone number or E-MAIL are invalid\nPlease contact call center : 021 613 000\nAT 9:00 – 18:00",
  inputotp_text_01: "OTP is sent to",
  inputotp_text_02: "OTP is sent to",
  inputotp_text_03: "Reference code",
  inputotp_text_04: "OTP password",
  inputotp_text_05: "Did not receive OTP",
  inputotp_text_06: "Send again",
  inputotp_text_07: "Login",
  home_text_01: "Welcome",
  home_text_02: "News & Events",
  home_text_03: "HOME",
  home_text_04: "HOME DATA",
  home_text_05: "ACCOUNT",
  notify_text_01: "Notification",
  notify_text_02: "All",
  notify_text_03: "News",
  notify_text_04: "Request Maintenance Service",
  notify_text_05: "Read all",
  account_text_01: "Account",
  account_text_02: "Personal Information",
  account_text_03: "Manage Resident / Tenants Information",
  account_text_04: "Language",
  account_text_05: "Privacy Policy ",
  account_text_06: "Call Center",
  account_text_07: "Sign Out",
  account_text_08: "Version",
  account_text_09: "Confirm",
  account_text_10: "Cancel",
  account_text_11: "Confirm Sign Out .",
  profile_text_01: "Personal Information",
  profile_text_02: "Name - Surname",
  profile_text_03: "Telephone",
  profile_text_04: "Save",
  profile_text_05: "Cancel",
  myhome_text_01: "Land size",
  myhome_text_02: "sq.Wa",
  myhome_text_03: "Usable area",
  myhome_text_04: "sq.m",
  myhome_text_05: "Request Maintenance Service",
  homecare_text_01: "Request Maintenance Service",
  homecare_text_02: "Home Address",
  homecare_text_03: "List of maintenance",
  homecare_text_04: "History",
  homecare_text_05: "No maintenance notice",
  homecare_text_06: "Add item",
  homecare_text_07: "Case number",
  homecare_text_08: "Amount",
  homecare_text_09: "Date and time for maintenance",
  homecare_text_10: "Date and time to service appointment",

}

const settingLanguage = (lang) => {
  var setting_LANG;
  if(lang === "TH"){
    setting_LANG = TH
  } else if (lang === "EN") {
    setting_LANG = EN
  } else {
    setting_LANG = TH
  }
  return setting_LANG
}

export default {
  settingLanguage
}

